### ISSUE TITLE
Instructions aren't clear

### ISSUE THREAD

**Issue by stretchkerr** [mikepound/enigma#2]
I'm a novice, having not done any programming in 20 years. I've installed JDK, and compiled Main.java.

When I run java com.mikepound.Main, I get:

Exception in thread "main" java.lang.NullPointerException
        at java.io.Reader.<init>(Unknown Source)
        at java.io.InputStreamReader.<init>(Unknown Source)
        at com.mikepound.analysis.fitness.BigramFitness.<init>(BigramFitness.java:21)
        at com.mikepound.Main.main(Main.java:14)
        
I don't understand how to "create a java enigma" using a constructor

"enigmaMachine = new Enigma(new String[] {"VII", "V", "IV"}, "B", new int[] {10,5,12}, new int[] {1,2,3}, "AD FT WH JO PN");"

If you could dumb down your instructions for the absolute rookies among us, that would be awesome.

**Comment by mikepound** [comment]
Hi, the issue here is a little complex - basically the BigramFitness and other fitness loaders use text files to retrieve the log probabilities of characters. These are held and loaded relative to the class path:

BigramFitness.class.getResourceAsStream("/data/bigrams");

The method you're using to run the main file isn't loading the class path such that it can find this bigrams file. I'll do some testing and see if I can work out the correct command you want to use to do this, then I can update the readme. I'll admit it's been a very long time since I compiled and ran java by hand on the command line!

While you wait I would strongly recommend installing IntelliJ Community Edition, which will load this project up and should get things compiling and running very easily. I used IntelliJ to write the project, so all the files are in the correct place for this.

**Comment by mikepound** [comment]
Right I've got a working set of a commands - haven't compiled java by hand for 10 years! This is for windows, I'll add this and Unix/Linux to the readme soon.

Clone and traverse into the enigma directory
```
git clone https://github.com/mikepound/enigma.git
cd enigma
```

Compile all the java files from src into bin
```
javac -d bin -sourcepath src src\com\mikepound\Main.java
```

Copy the n-gram statistics into the bin folder too 
```
xcopy resources\data bin\data\
```

Run the Enigma code in main
```
java -cp bin com.mikepound.Main
```

Output
I II III
I II IV
I II V
etc.

**Comment by PavloMcBlister** [comment]
Thanks for the command line instructions. I have a M1 Mac Mini. This ran in 19573 ms. I have no idea how that compares to anything else.

**Comment by mikepound** [comment]
Seriously fast compared to my thinkpad!

**Comment by mikepound** [comment]
Right I've added a little more by way of instructions to the readme (491dce9) - I'll close this one for now.

**Comment by stretchkerr** [comment]
Thanks Mike, I've got it working via your command line instructions. IntelliJ threw a bunch of errors. "package org.junit.jupiter.api does not exist", so I'll stick with old-school command line for now.
