### ISSUE TITLE
When some plaintext is known?

### ISSUE THREAD

**Issue by byteduty** [mikepound/enigma#3]
Hi Mike,

Love the videos, and in this case its great that you have provided the code. Brilliant!

Anyway, I'm not a Java developer, but I'm trying to get through this with my C and Python knowledge. I was trying to see if I could get known bits of plain text to improve the matching of the settings? The idea being that once you've got the sudo text out, if you can identify strings that you think are correct, you can feed these back in.

I tried adding this in, but I may be well off on what I'm doing here (Java at least part of the barrier). Any chance of an example involving some plain text, and how it might improve finding the settings?

```Java
+      String[] known_str=new String[] {"PROPOSE", "CONSIDER", "QUESTION"};
+      int[] intArray = new int[] { 1, 10, 21};
        FitnessFunction ioc = new IoCFitness();
        FitnessFunction bigrams = new BigramFitness();
        FitnessFunction quadgrams = new QuadramFitness();
 +     FitnessFunction knownplain = new KnownPlaintextFitness(known_str, intArray);
```
Oh, and another quick question, in your example decrypted text, it looked (although its not fully decoded) like there are no spaces, I know that Enigma didn't have spaces, but I've read other places that someone could use `X`. Is the presence of `X`s as spaces or something else a vulnerability to the encoding?
Colin

**Comment by mikepound** [comment]
Hi Colin,

You're very much on the right lines here - I can't see any issues with your code, as long as you're actually using the knownplain object as part of the analysis later. The reason you might not see it making any difference is because the other fitness functions are already doing an adequate job of finding the best possible settings (under the circumstances). This is mostly because this is a slightly contrived example, long ciphertext, only 5 plugs. My experience testing out my code as I wrote it was that this is a noisy process, even just changing the plugs or adding a single plug extra can totally change how the fitness functions react. I found that plaintext fitness (with a few words, maybe 5?) was a lot more stable. But I haven't explored this fully.

In terms of if you can improve the matching settings further, probably not the way the attack is right now. Becase we are fixing the ring settings, the match is unlikely to be perfect for a message of this length. Once you got the best rotor settings, you could go back and optimise the ring settings and start positions simultaneously, which would find the perfect setting. This attack would be ~26^5, which is doable if you use the multi-threaded code in the other branch.

To your final question, I decided for ease of use and the video I'd just encrypt basic English text. You're right that of course during the war the messages were German, but also used X for space, and a few other things. If you attempt to decrypt messages like this it'll work, but your fitness functions won't be quite as good, because all of the likelihoods are based around standard English. If you created some log likelihood tables for german war messages, that would be more effectively. As expected, the same is true for other languages. For this to be as effective on French, for instance, would require new statistics for the fitness functions.

**Comment by mikepound** [comment]
I've added a bit more on plaintext fitness to the main readme. f9b7c36

**Comment by byteduty** [comment]
Excellent.

Colin


On 7 May 2021 22:04:05 BST, Michael Pound ***@***.***> wrote:
>I've added a bit more on plaintext fitness to the main readme. f9b7c36
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mikepound/enigma/issues/3#issuecomment-834778353

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
